class Commands:
    LEECH = "leech@EchidaBot"
    PURGE = "purge@EchidaBot"
    PAUSEALL = "pauseall@EchidaBot"
    RESUMEALL = "resumeall@EchidaBot"
    STATUS = "status@EchidaBot"
    SETTINGS = "settings@EchidaBot"
    EXEC = "exec@EchidaBot"
    UPLOAD = "upload@EchidaBot"
    YTDL = "ytdl@EchidaBot"
    PYTDL = "pytdl@EchidaBot"
    ABOUT = "about@EchidaBot"
    GETLOGS = "getlogs@EchidaBot"
    SERVER = "server@EchidaBot"
    USERSETTINGS = "usetting@EchidaBot"
    INSTADL = "instadl@EchidaBot"
